
name: Build Tests

on: [pull_request]

jobs:
  Build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config: 
          - {
            name: "Windows/X64/Release",
            os: windows-latest,
            config: Release,
            args: -G "Visual Studio 17 2022" -A x64,
          }
    steps:
      - uses: actions/checkout@v3     
      - run: git submodule update --init --recursive
      - run: |
          mkdir build
          mkdir library_binaries

          cd external\ai-library
          mkdir build
          cd build
          cmake ${{ matrix.config.cmake_extra_args }} -DCMAKE_BUILD_TYPE=${{ matrix.config.config }} -S ./../ -B /build -DCMAKE_PREFIX_PATH=D:/a/Artificial-Intelligence/Artificial-Intelligence/library_binaries
          cmake --build . --config ${{ matrix.config.config }} --parallel
          cmake --install . --prefix ./../../../library_binaries --config ${{ matrix.config.config }}
          cd ./../../../

          cd external\sdl-2.24.2
          mkdir build
          cd build
          cmake ${{ matrix.config.cmake_extra_args }} -DCMAKE_BUILD_TYPE=${{ matrix.config.config }} -S ./../ -B /build -DCMAKE_PREFIX_PATH=D:/a/Artificial-Intelligence/Artificial-Intelligence/library_binaries
          cmake --build . --config ${{ matrix.config.config }} --parallel
          cmake --install . --prefix ./../../../library_binaries --config ${{ matrix.config.config }}
          cd ./../../../

          cd external\sdl-image-2.6.2
          mkdir build
          cd build
          cmake ${{ matrix.config.cmake_extra_args }} -DCMAKE_BUILD_TYPE=${{ matrix.config.config }} -S ./../ -B /build -DCMAKE_PREFIX_PATH=D:/a/Artificial-Intelligence/Artificial-Intelligence/library_binaries
          cmake --build . --config ${{ matrix.config.config }} --parallel
          cmake --install . --prefix ./../../../library_binaries --config ${{ matrix.config.config }}
          cd ./../../../

          cd external\sdl-mixer-2.6.2
          mkdir build
          cd build
          cmake ${{ matrix.config.cmake_extra_args }} -DCMAKE_BUILD_TYPE=${{ matrix.config.config }} -S ./../ -B /build -DCMAKE_PREFIX_PATH=D:/a/Artificial-Intelligence/Artificial-Intelligence/library_binaries
          cmake --build . --config ${{ matrix.config.config }} --parallel
          cmake --install . --prefix ./../../../library_binaries --config ${{ matrix.config.config }}
          cd ./../../../

          cd external\sdl-ttf-2.20.1
          mkdir build
          cd build
          cmake ${{ matrix.config.cmake_extra_args }} -DCMAKE_BUILD_TYPE=${{ matrix.config.config }} -S ./../ -B /build -DCMAKE_PREFIX_PATH=D:/a/Artificial-Intelligence/Artificial-Intelligence/library_binaries
          cmake --build . --config ${{ matrix.config.config }} --parallel
          cmake --install . --prefix ./../../../library_binaries --config ${{ matrix.config.config }}
          cd ./../../../

          cd build
          cmake ${{ matrix.config.cmake_extra_args }} -DCMAKE_BUILD_TYPE=${{ matrix.config.config }} -S ./../ -DCMAKE_PREFIX_PATH=D:/a/Artificial-Intelligence/Artificial-Intelligence/library_binaries
          cmake --build . --config ${{ matrix.config.config }} --parallel
          cmake --install . --prefix ./../../../library_binaries --config ${{ matrix.config.config }}
          echo Project built successfully