name: Build Tests
on: [pull_request]
jobs:
  Build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config: 
          - {
            name: "Windows/X64/Release",
            os: Windows,
            config: Release,
            args: -G "Visual Studio 17 2022" -A x64,
          }
    steps:
      - uses: actions/checkout@v3     
      - run: git submodule update --init --recursive
      - run: |
          cd ./build-scripts
          build-repo.bat