name: Build (Windows)
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  Build:
    name: ${{ matrix.config.name }}
    runs-on: Windows
    strategy:
      fail-fast: false
      matrix:
        config: 
          - {
            name: "MSVC",
            config: Release,
            args: -G "Visual Studio 16 2019",
            prefixpath: "C:/actions-runner/_work/Carlos-Dungeon-Crusade/Carlos-Dungeon-Crusade/library_binaries"
          }
    steps:
      - name: Checkout code
        uses: actions/checkout@v3    
        
      - name: Install Dependencies
        run: |
          git submodule update --init --recursive

      - name: Build Dependencies
        run: |
          mkdir -force build; mkdir -force library_binaries
          $dependencies = @("ai-library", "sdl-2.24.2", "sdl-image-2.6.2", "sdl-mixer-2.6.2", "sdl-ttf-2.20.1")
          foreach ($dep in $dependencies) {
            Set-Location external/$dep
            mkdir -force build | Out-Null
            Set-Location build
            cmake ${{ matrix.config.args }} -DCMAKE_BUILD_TYPE=${{ matrix.config.config }} -S ../ -B ../build -DCMAKE_PREFIX_PATH=${{ matrix.config.prefixpath }} ${{ matrix.config.compiler }}
            cmake --build . --config ${{ matrix.config.config }} --parallel
            cmake --install . --prefix ${{ matrix.config.prefixpath }} --config ${{ matrix.config.config }}
            Set-Location ../../..
          }

      - name: Build Project
        run: |
          cd build
          cmake ${{ matrix.config.args }} -DCMAKE_BUILD_TYPE=${{ matrix.config.config }} -S ../ -DCMAKE_PREFIX_PATH=${{ matrix.config.prefixpath }} ${{ matrix.config.compiler }}
          cmake --build . --config ${{ matrix.config.config }} --parallel
